empty?: "%{name} cannot be empty"

exclusion?: "%{name} must not be one of: %{list}"

filled?: "%{name} must be filled"

gt?: "%{name} must be greater than %{num} (%{value} was given)"

gteq?: "%{name} must be greater than or equal to %{num}"

inclusion?: "%{name} must be one of: %{list}"

int?: "%{name} must be an integer"

key?: "%{name} is missing"

lt?: "%{name} must be less than %{num} (%{value} was given)"

lteq?: "%{name} must be less than or equal to %{num}"

max_size?: "%{name} size cannot be greater than %{num}"

min_size?: "%{name} size cannot be less than %{num}"

nil?: "%{name} cannot be nil"

size?:
  range: "%{name} size must be within %{left} - %{right}"
  default: "%{name} size must be %{num}"

str?: "%{name} must be a string"
